name: Minor or Major Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: Release type
        required: true
        type: choice
        options:
          - minor
          - major

permissions:
  contents: write

jobs:
  milestone-release:
    name: Minor or Major Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Enable Corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22
          cache: yarn

      - name: Install
        run: yarn install --immutable

      - name: Lint
        run: yarn lint

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Milestone Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: node scripts/manual-release.mjs ${{ inputs.release_type }}
